<?php

return [
    'home' => 'web-views.home',
    'product_search_result' => 'web-views.partials._search-result',
    'privacy_policy_page' => 'web-views.pages.privacy-policy',
    'refund_policy_page' => 'web-views.pages.refund-policy',
    'return_policy_page' => 'web-views.pages.return-policy',
    'terms_conditions_page' => 'web-views.pages.terms-conditions',
    'cancellation_policy_page' => 'web-views.pages.cancellation-policy',
    'user_account' => 'web-views.users-profile.user-account',
    'user_profile' => '',
    'account_address_add' => '',
    'account_address_edit' => 'web-views.users-profile.account-address-edit',
    'account_orders' => 'web-views.users-profile.account-orders',
    'order_invoice' => 'web-views.order.invoice',
    'account_order_details' => 'web-views.users-profile.account-order-details',
    'refund_details' => 'web-views.users-profile.refund-details',
    'seller_info' => 'web-views.users-profile.account-details.seller-info',
    'delivery_man_info' => 'web-views.users-profile.account-details.delivery-man-info',
    'order_details_review'=>'web-views.users-profile.account-details.reviews',
    'track_order_wise_result'=>'web-views.users-profile.account-details.track-order',
    'tracking-page' =>'web-views.order.tracking-page',
    'track_order' => 'web-views.order.tracking',
    'account_wishlist' => 'web-views.users-profile.account-wishlist',
    'account_compare_list'=>'',
    'account_wishlist_partials' => 'web-views.partials._wish-list-data',
    'user_wallet' => 'web-views.users-profile.user-wallet',
    'user_loyalty' => 'web-views.users-profile.user-loyalty',
    'account_tickets' => 'web-views.users-profile.account-tickets',
    'ticket_view' => 'web-views.users-profile.ticket-view',
    'user_inbox' => 'web-views.users-profile.user-inbox',
    'seller_registration'=>'seller-views.auth.register',
    'all_stores_page'=>'web-views.sellers',
    'customer_auth_verify'=>'customer-view.auth.verify',
    'products_details'=>'web-views.products.details',
    'products'=>'web-views.products',
    'products_cart_partials'=>'layouts.front-end.partials.cart',
    'products_floating_nav_partials' =>'',
    'products_cart_details_partials'=>'layouts.front-end.partials.cart_details',
    'product_reviews_partials'=>'web-views.partials.product-reviews',
    'product_quick_view_partials'=>'web-views.partials._quick-view-data',
    'cart_list'=>'web-views.shop-cart',
    'order_shipping'=>'web-views.checkout.shipping',
    'payment_details'=>'web-views.checkout.payment',
    'marcedo_pogo'=>'web-views.payment.marcedo-pogo',
    'payment_payment'=>'payment.paytm',
    'order_complete'=>'web-views.checkout.complete',
    'mobile_app_payment_view'=>'web-views.mobile-app-view.payment',
    'my-cart-address'=>'web-views.my-cart-address',
    'my-cart-added'=>'web-views.my-cart-added',
    'add-payment'=>'web-views.add-payment',
    'my-shortlist'=>'web-views.my-shortlist',
    'product-detail'=>'web-views.product-detail',
    'my-profile' => 'web-views.my-profile',
    'my-order' => 'web-views.my-order',
    'manage-returns'=>'web-views.manage-returns',
    'return-detail'=>'web-views.return-detail',
    'quick-reorder'=>'web-views.quick-reorder',
    'order-available'=>'web-views.order-available',
    'track-orders'=>'web-views.track-orders',
    'your-query'=>'web-views.your-query',
    'cash-refund'=>'web-views.cash-refund',
    'my-payment-detail-not-added'=>'web-views.my-payment-detail-not-added',
    'my-payment-detail-added'=>'web-views.my-payment-detail-added',
    'save-cards'=>'web-views.save-cards',
    'cash-coupons'=>'web-views.cash-coupons',
    'cash-back-codes'=>'web-views.cash-back-codes',
    'my-refund-no-refund'=>'web-views.my-refund-no-refund',
    'my-refund'=>'web-views.my-refund',
    'my-bpl-vouchers'=>'web-views.my-bpl-vouchers',
    'guaranteed-savings'=>'web-views.guaranteed-savings',
    'guaranteed-savings-offer'=>'web-views.guaranteed-savings-offer',   
    'guaranteed-savings-offer-brand'=>'web-views.guaranteed-savings-offer-brand',
    'intelli-education'=>'web-views.intelli-education',
    'gift-certification'=>'web-views.gift-certification',
    'invites-credits'=>'web-views.invites-credits',
    'my-reviews-upload'=>'web-views.my-reviews-upload',
    'categories'=>'web-views.categories',
    'sub-category'=>'web-views.sub-category',





    





    'products_mobile_nav_partials'=>'layouts.front-end.partials.cart',
    'products_view_page'=>'web-views.products.view',
    'products__ajax_partials'=>'web-views.products._ajax-products',
    'all_brands'=>'web-views.brands',
    'contacts'=>'web-views.pages.contact-us',
    'flash_deals'=>'web-views.deals',
    'shop_view_page'=>'web-views.shop-page',
    'faq'=>'web-views.pages.help-topics',
    'about_us'=>'web-views.pages.about-us',
    'recover_password'=>'customer-view.auth.recover-password',
    'otp_verification'=>'customer-view.auth.verify-otp',
    'reset_password'=>'customer-view.auth.reset-password',
    'wallet_account' => '',
    'product_search_result_for_compare_list'=>'',
    'maintenance_mode'=>'web-views.maintenance-mode',
    'refer_earn'=>'web-views.users-profile.refer-earn',
    'user_coupons'=>'web-views.users-profile.coupons',
    'pay_offline_method_list_partials'=>'web-views.partials._pay_offline_method_list_fields',
    'digital_product_order_otp_verify'=>'layouts.front-end.partials._digital-product-order-otp-verify',
    'digital_product_order_otp_verify_failed'=>'layouts.front-end.partials._digital-product-order-otp-verify-failed',
];
